openapi: 3.0.0
info:
  title: Purchase Transaction API
  version: 1.0.0
  description: API for managing and converting purchase transactions

paths:
  /api/purchases:
    post:
      summary: Create a new purchase transaction
      tags:
        - Purchase Transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseTransaction'
      responses:
        '200':
          description: Successfully created the purchase transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseTransaction'
        '412':
          description: Precondition Failed - State of transaction is NOT_ACCEPT
        '400':
          description: Bad Request - Invalid data

    get:
      summary: Retrieve all purchase transactions
      tags:
        - Purchase Transaction
      responses:
        '200':
          description: Successfully retrieved all purchase transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseTransaction'

  /api/purchases/{transactionId}:
    get:
      summary: Retrieve a specific purchase transaction by ID
      tags:
        - Purchase Transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully retrieved the purchase transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseTransaction'
        '404':
          description: Purchase transaction not found

    put:
      summary: Update an existing purchase transaction
      tags:
        - Purchase Transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseTransaction'
      responses:
        '200':
          description: Successfully updated the purchase transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseTransaction'
        '404':
          description: Purchase transaction not found

    delete:
      summary: Delete a purchase transaction
      tags:
        - Purchase Transaction
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Successfully deleted the purchase transaction
        '404':
          description: Purchase transaction not found

  /api/transactions/{transactionId}/convert:
    get:
      summary: Convert a purchase transaction amount to a target currency
      tags:
        - Currency Conversion
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: targetCurrency
          in: query
          required: true
          schema:
            type: string
          description: Target currency to convert the transaction amount to
      responses:
        '200':
          description: Successfully converted the transaction amount
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseTransactionConversionDto'
        '404':
          description: Transaction not found
        '400':
          description: Currency conversion rate not available within the last 6 months for the specified currency

components:
  schemas:
    PurchaseTransaction:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
        description:
          type: string
        transactionDate:
          type: string
          format: date-time
        amountUSD:
          type: number
          format: double
        state:
          type: string
          enum:
            - ACCEPT
            - NOT_ACCEPT
      required:
        - description
        - transactionDate
        - amountUSD
        - state

    PurchaseTransactionConversionDto:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
        description:
          type: string
        transactionDate:
          type: string
          format: date-time
        amountUSD:
          type: number
          format: double
        exchangeRate:
          type: number
          format: double
        convertedAmount:
          type: number
          format: double
      required:
        - transactionId
        - description
        - transactionDate
        - amountUSD
        - exchangeRate
        - convertedAmount
